### ISSUE TITLE
What is the  aux_feats in zsl_methods_imagenet/CADA-VAE/configs/example_env_config.yml

### ISSUE THREAD

**Issue by NanAlbert** [sebastianbujwid/zsl_methods_imagenet#1]
Hello, I am interested in your work and try to implement zero-shot learning in ImageNet datasets. But I find that aux_feats is unknown. Can you give more detailed information, such as what it is and how to get it? I look forward to hearing from you. Thank you so much!

**Comment by sebastianbujwid** [comment]
Hey!

The `aux_feats` are pickle files with encoded features for each Wikipedia article.
There are different versions of them: for different sets of classes and different types of encoding of the text.

Due to some storage migration the old links to `aux_feats` files have actually expired and I had to update them! They should be working now.

See the commit: [dac0385](https://github.com/sebastianbujwid/zsl_methods_imagenet/commit/dac0385d853a0613a8d8864aa79f8b5d1bf1a49d)

Hope that clarifies!
